### ISSUE TITLE
Cannot find module 'Pattern'

### ISSUE THREAD

**Issue by pepe79** [KnisterPeter/patternplate-transform-typescript#1]
Using the documented way to import the current pattern to use it in a demo fails, because module 'Pattern' cannot be resolved.

`import Button from 'Pattern'
`

leads to 

`demo.tsx (2,24): Cannot find module 'Pattern'
`

Also imports from referenced Patterns in pattern.json, lead to a console-error, which are apparently irrelevant, because the Pattern is displayed correctly in patternplate frontend.

**Comment by KnisterPeter** [comment]
> Also imports from referenced Patterns in pattern.json, lead to a console-error, which are apparently irrelevant, because the Pattern is displayed correctly in patternplate frontend
This is a separate issue. You can get around this by configuring the tsc in a special manner with the path directive.
