### ISSUE TITLE
dependency resolving in generated type definition files 

### ISSUE THREAD

**Issue by rgaertner** [KnisterPeter/patternplate-transform-typescript#10]
resolve dependency path are not respected in generated type definitions.

**Comment by KnisterPeter** [comment]
The created definition files must be processed by the [resolve-imports transform](https://github.com/sinnerschrader/patternplate-transform-resolve-imports).

**Comment by KnisterPeter** [comment]
After talking to @marionebl this will not be solved by patternplate, since artifacts are in the responsibility of the attaching transform.
