### ISSUE TITLE
Compiled d.ts do not correspond the pattern implementation

### ISSUE THREAD

**Issue by Palmaswell** [KnisterPeter/patternplate-transform-typescript#6]
We are trying to execute the build task. Some patterns (not all of them) are not receiving the proper typing definitions. This includes the module exports too. 

## Dev Pattern
This is an example of one of the develop patterns.
![pattern-compiled](https://cloud.githubusercontent.com/assets/3357315/25814414/b3d96c08-341d-11e7-9e31-c686dddf46f4.png)

## Compiled Pattern
This would be the compilation result. 
![pattern-compiled](https://cloud.githubusercontent.com/assets/3357315/25814332/68a6c50a-341d-11e7-885f-b28d3cf3c890.png)
As you can see, the exports do not include the typings of the components. What might be important to note is that the compiled `d.ts` is actually the typing and exports of a completely different component (see below screenshot).

![screen shot 2017-05-08 at 18 44 07](https://cloud.githubusercontent.com/assets/3357315/25814590/5b77be9c-341e-11e7-868e-b3914ae43045.png)

**Comment by Palmaswell** [comment]
It might be worth notice that when we currently execute our build command we get in the console following error message: 

`Cannot find name 'exports'`
` Cannot find name 'process'`

But at the end receive:
```
✔ 25/25 built
✔ static files copied
info:  taskName "build-commonjs" executed successfully
```

**Comment by KnisterPeter** [comment]
Two things to note here:
* First, as recommended by Microsoft, please use `interface` instead of `type` whenever possible.
* You need to export the types as well. So this might work better:

```typescript
export interface CompProps {
   prop?: 'a' | 'b';
}
const Comp = (props: CompProps) => (
  <div>{this.props.prop}</div>
);
export default Comp;
```
